sudo: required
dist: trusty
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
language: node_js
node_js:
  - "6"
cache:
  - node_modules
before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
install:
  - npm install
  - npm install @ckeditor/ckeditor5-dev-tests
script:
  - node_modules/.bin/ckeditor5-dev-tests --ignore-duplicates --files=autoformat/**/*.js
  - node_modules/.bin/ckeditor5-dev-tests --ignore-duplicates --files=basic-styles/**/*.js
  - node_modules/.bin/ckeditor5-dev-tests --ignore-duplicates --files=core/**/*.js
  - node_modules/.bin/ckeditor5-dev-tests --ignore-duplicates --files=engine/**/*.js
  - node_modules/.bin/ckeditor5-dev-tests --ignore-duplicates --files=enter/**/*.js
  - node_modules/.bin/ckeditor5-dev-tests --ignore-duplicates --files=heading/**/*.js
  - node_modules/.bin/ckeditor5-dev-tests --ignore-duplicates --files=list/**/*.js
  - node_modules/.bin/ckeditor5-dev-tests --ignore-duplicates --files=paragraph/**/*.js
  - node_modules/.bin/ckeditor5-dev-tests --ignore-duplicates --files=ui/**/*.js
  - node_modules/.bin/ckeditor5-dev-tests --ignore-duplicates --files=ui-default/**/*.js
  - node_modules/.bin/ckeditor5-dev-tests --ignore-duplicates --files=utils/**/*.js
