#!/usr/bin/env node

'use strict';

const fs = require( 'fs' );
const path = require( 'path' );
const glob = require( 'glob' );

const srcDir = path.join( process.cwd(), 'src' );
const srcPath = path.join( srcDir , '**', '*.js' );
for ( const filePath of glob.sync( srcPath ) ) {
	if ( filePath.includes( '-fixed' ) ) {
		fs.unlinkSync( filePath );

		continue;
	}

	const fileDepth = countOcurrences( filePath.replace( srcDir + '/', '' ), path.sep );
	const fix = ( wholeImport, pathStart ) => fixImport( wholeImport, pathStart, fileDepth );

	const fileContent = fs.readFileSync( filePath, 'utf-8' )
		.replace( /import\s*\{[^\}]+}\s*from\s*'((\.\.\/)+[\w-]+)\/[^']+'/g,  fix )
		.replace( /import\s*[\w]+\s*from\s*'((\.\.\/)+[\w-]+)\/[^']+'/g, fix )
		.replace( /import\s*\*\s*as\s*[\w]+\s*from\s*'((\.\.\/)+[\w-]+)\/[^']+'/g, fix );

	const newFileName = filePath.split( '.' ).slice( 0, -1 ).join( '.' );
	fs.writeFileSync( newFileName + '-fixed.js', fileContent , 'utf-8' );
}

function fixImport( wholeImport, pathStart, fileDepth ) {
	const indexOfPathStart = wholeImport.indexOf( '../' );
	const packageShortName = pathStart.split( '/' ).slice( -1 )[0];
	const importDepth = countOcurrences( pathStart, '../' );

	if ( importDepth < fileDepth ) {
		return wholeImport;
	}

	return (
		wholeImport.slice( 0, indexOfPathStart ) +
		'ckeditor5-' + packageShortName +
		'/src' +
		wholeImport.slice( indexOfPathStart + pathStart.length )
	);
}

function countOcurrences( str, pattern ) {
	return str.split( pattern ).length - 1;
}
